name: Lint (ShellCheck)

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          
          curl -sS https://webi.sh/shfmt | sh 
          source ~/.config/envman/PATH.env
          shfmt --version

      - name: shfmt (check formatting)
        run: |
          shfmt -i 2 -ci -bn -d vectored.sh lib/*.sh

      - name: ShellCheck
        run: |
          shellcheck -x vectored.sh lib/*.sh